fname = input('Enter first name: ')
lname = input('Enter last name: ')
add = input('Enter address: ')
cit = input('Enter city: ')
st = input('Enter state: ')
co = input('Enter postal code: ')
print('\n')
print(fname + " " + lname)
print(add)
print(cit + " " + st + " " + co)
