from turtle import *

def c01():
    bgcolor('grey')
    shape ('arrow')
    fillcolor('white')
    begin_fill()
    speed (4)
    circle(175,360)
    penup()
    setposition(0,0)
    end_fill()
    pendown()
    
def c02():
    fillcolor('red')
    begin_fill()
    penup()
    goto(-75,175)
    pendown()
    circle(35,360)
    setposition(-75,175)
    end_fill()
    #-----------------------------------
    fillcolor('blue')
    begin_fill()
    penup()
    goto(75,175)
    pendown()
    circle(35,360)
    setposition(75,175)
    end_fill()
    #-----------------------------------
    fillcolor('yellow')
    begin_fill()
    penup()
    goto(60,100)
    setheading(90)
    pendown()
    circle(60,-180)
    setposition(60,100)
    end_fill()
    penup()
    #------------------------------
    fillcolor('purple')
    begin_fill()
    goto(45,150)
    pendown()
    shape('arrow')
    forward(20)
    right(90)
    forward(95)
    right(90)
    forward(20)
    right(90)
    forward(95)
    end_fill()
    penup()

def main():
    c01()
    c02()
main()
